def english():
    english_quotes = [
        "Be the change you wish to see in the world. - Mahatma Gandhi",
        "It does not matter how slowly you go as long as you do not stop. - Confucius",
        "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world. - Albert Einstein",
        "Believe you can and you're halfway there. - Theodore Roosevelt",
        "The only way to do great work is to love what you do. - Steve Jobs",
        "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
        "I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
        "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
        "Life is 10% what happens to us and 90 percent how we react to it. - Charles R. Swindoll",
        "We become what we think about. - Earl Nightingale",
        "The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
        "The best way to predict the future is to invent it. - Alan Kay",
        "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
        "Love all, trust a few, do wrong to none. - William Shakespeare",
        "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
        "Be yourself; everyone else is already taken. - Oscar Wilde",
        "Try not to become a man of success, but rather try to become a man of value. - Albert Einstein",
        "We must be the change we wish to see in the world. - Mahatma Gandhi",
        "We can't help everyone, but everyone can help someone. - Ronald Reagan",
        "If you want to live a happy life, tie it to a goal, not to people or things. - Albert Einstein",
        "You miss 100 percent of the shots you don't take. - Wayne Gretzky",
        "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
        "I would rather die of passion than of boredom. - Vincent van Gogh",
        "It is not in the stars to hold our destiny but in ourselves. - William Shakespeare",
        "I have a dream that one day this nation will rise up and live out the true meaning of its creed: 'We hold these truths to be self-evident, that all men are created equal.' - Martin Luther King Jr.",
        "Failure is not an option. Everyone has to succeed. - Arnold Schwarzenegger",
        "The best revenge is massive success. - Frank Sinatra",
        "I believe that if one always looks at the skies, one will end up with wings. - Gustave Flaubert",
        "The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
        "Logic will get you from A to B. Imagination will take you everywhere. - Albert Einstein",
        "Peace begins with a smile. - Mother Teresa",
        "Don't let yesterday take up too much of today. - Will Rogers",
        "Be the type of person you want to meet. - Unknown",
        "You can have everything in life you want, if you will just help enough other people get what they want. - Zig Ziglar",
        "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
        "The mind is everything. What you think you become. - Buddha",
        "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world. - Buddha",
        "It is during our darkest moments that we must focus to see the light. - Aristotle Onassis",
        "Your present circumstances don't determine where you can go; they merely determine where you start. - Nido Qubein",
        "Everything has beauty, but not everyone sees it. - Confucius",
        "If you tell the truth, you don't have to remember anything. - Mark Twain",
        "Don't let what you cannot do interfere with what you can do. - John Wooden",
        "Success consists of going from failure to failure without loss of enthusiasm. - Winston Churchill",
        "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
        "You can't change the direction of the wind, but you can adjust your sails to always reach your destination. - Jimmy Dean",
        "If you don't stand for something, you will fall for anything. - Malcolm X",
        "The unexamined life is not worth living. - Socrates",
        "It is hard to fail, but it is worse never to have tried to succeed. - Theodore Roosevelt",
        "The greatest glory in living lies not in never falling, but in rising every time we fall. - Ralph Waldo Emerson",
        "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
        "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
        "I've failed over and over and over again in my life and that is why I succeed. - Michael Jordan",
        "We must accept finite disappointment, but never lose infinite hope. - Martin Luther King Jr.",
        "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa",
        "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
        "Keep your face always toward the sunshine - and shadows will fall behind you. - Walt Whitman",
        "You are never too old to set another goal or to dream a new dream. - C. S. Lewis",
        "What we think, we become. - Buddha",
        "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
        "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
        "The only true wisdom is in knowing you know nothing. - Socrates",
        "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
        "Life is a series of natural and spontaneous changes. Don't resist them - that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like. - Lao Tzu",
        "The only way to have a good idea is to have a lot of ideas. - Linus Pauling",
        "Strive not to be a success, but rather to be of value. - Albert Einstein",
        "If you want to make your dreams come true, the first thing you have to do is wake up. - J. M. Power",
        "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
        "We may encounter many defeats but we must not be defeated. - Maya Angelou",
        "Be the change that you wish to see in the world. - Mahatma Gandhi",
        "A little knowledge that acts is worth infinitely more than much knowledge that is idle. - Kahlil Gibran",
        "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
        "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller",
        "All our dreams can come true, if we have the courage to pursue them. - Walt Disney",
        "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
        "It always seems impossible until it's done. - Nelson Mandela",
        "Courage doesn't always roar. Sometimes courage is the quiet voice at the end of the day saying 'I will try again tomorrow.' - Mary Anne Radmacher",
        "The only thing standing between you and your goal is the bullshit story you keep telling yourself as to why you can't achieve it. - Jordan Belfort",
        "Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them. - William Shakespeare",
        "A man is but the product of his thoughts. What he thinks, he becomes. - Mahatma Gandhi",
    ]
    return english_quotes