def uzbek():
    uzbek_quotes = ["Dunyoda ko'rishni xohlagan o'zgarish bo'l. - Mahatma Gandi",
                    "To'xtamaguningizcha qanchalik sekin borishingiz muhim emas. - Konfutsiy",
                    "Tasavvur bilimdan muhimroqdir. Bilim cheklangan. Tasavvur dunyoni o'rab oladi. - Albert Eynshteyn",
                    "Ishoning, qila olasiz va siz yarim yo'ldasiz. - Teodor Ruzvelt",
                    "Buyuk ish qilishning yagona yo'li - qilayotgan ishingizni sevishdir. - Stiv Jobs",
                    "Oxir-oqibat, biz dushmanlarimizning so'zlarini emas, balki do'stlarimizning sukutini eslaymiz. - Martin Lyuter King Jr.",
                    "Men muvaffaqiyatsizlikka uchramadim. Men ishlamaydigan 10 000 ta usulni topdim. - Tomas Edison",
                    "Muvaffaqiyat yakuniy emas, muvaffaqiyatsizlik halokatli emas: davom etish uchun jasorat muhimdir. - Uinston Cherchill",
                    "Hayot 10% biz bilan nima sodir bo'lishidan va 90% biz bunga qanday munosabatda bo'lishimizdan iborat. - Charlz R. Svindoll",
                    "Biz o'ylagan narsamizga aylanamiz. - Erl Nightingale",
                    "Yomonlikning g'alabasi uchun zarur bo'lgan yagona narsa - bu yaxshi odamlar hech narsa qilmaslikdir. - Edmund Burk",
                    "Biz qayta-qayta qiladigan narsamiz. Demak, mukammallik - bu harakat emas, balki odat. - Aristotel",
                    "Kelajakni bashorat qilishning eng yaxshi usuli uni ixtiro qilishdir. - Alan Kay",
                    "Baxt bu tayyor narsa emas. Bu sizning harakatlaringizdan kelib chiqadi. - Dalay Lama",
                    "Hammasini sev, bir nechtasiga ishon, hech kimga yomonlik qil. - Uilyam Shekspir"
                    "Yashashdagi eng katta shon-sharaf hech qachon yiqilmasligimizda emas, balki har yiqilganimizda ko'tarilishimizdadir. - Nelson Mandela"
                    "O'zing bo'l; hamma allaqachon olingan. - Oskar Uayld",
                    "Muvaffaqiyatli odam bo'lishga emas, balki qadrli odam bo'lishga harakat qiling. - Albert Eynshteyn",
                    "Biz dunyoda ko'rishni istagan o'zgarish bo'lishimiz kerak. - Mahatma Gandi",
                    "Biz hammaga yordam bera olmaymiz, lekin hamma kimgadir yordam berishi mumkin. - Ronald Reygan",
                    "Agar siz baxtli hayot kechirishni istasangiz, uni odamlarga yoki narsalarga emas, balki maqsadga bog'lang. - Albert Eynshteyn",
                    "Siz suratga olmagan suratlarning 100 foizini o'tkazib yuborasiz. - Ueyn Gretzki",
                    "Men muvaffaqiyatimni shu bilan bog'layman: men hech qachon uzr bermaganman yoki bahona ham qilmaganman. - Florens Nightingale",
                    "Men zerikishdan ko'ra ehtirosdan o'lganni afzal ko'raman. - Vinsent van Gog",
                    "Taqdirimiz yulduzlarda emas, balki o'zimizda. - Uilyam Shekspir"
                    "Mening orzuim bir kun kelib, bu xalq bosh ko'tarib, o'z e'tiqodining asl ma'nosini hayotga tatbiq etsa: “Biz bu haqiqatlarni o'z-o'zidan ravshan deb bilamiz, barcha insonlar teng yaratilgan”. - Martin Lyuter King Jr.",
                    "Muvaffaqiyatsizlik - bu variant emas. Hamma muvaffaqiyatga erishishi kerak. - Arnold Shvartsenegger",
                    "Eng yaxshi qasos - bu katta muvaffaqiyat. - Frenk Sinatra",
                    "Men ishonamanki, agar inson doimo osmonga qarasa, qanotli bo'ladi. - Gustav Flober",
                    "Biz qo'rqishimiz kerak bo'lgan yagona narsa - qo'rquvning o'zi. - Franklin D. Ruzvelt",
                    "Mantiq sizni A dan B gacha olib boradi. Tasavvur sizni hamma joyga olib boradi. - Albert Eynshteyn",
                    "Tinchlik tabassumdan boshlanadi. - Tereza ona",
                    "Kechagi kun bugunning ko'p qismini egallashiga yo'l qo'ymang. - Uill Rojers",
                    "O'zingiz uchrashmoqchi bo'lgan odam turi bo'ling. - Noma'lum",
                    "Agar siz boshqa odamlarga xohlagan narsalarini olishiga yordam bersangiz, hayotda siz xohlagan hamma narsaga ega bo'lishingiz mumkin. - Zig Ziglar",
                    "Ertangi kunimizni anglashimizning yagona chegarasi bugungi kundagi shubhalarimiz bo'ladi. - Franklin D. Ruzvelt",
                    "Aql - bu hamma narsa. O'zingni o'ylagan narsang. - Budda",
                    "Biz o'ylagan narsamiz. Biz nima bo'lsak, hamma narsa bizning fikrlarimiz bilan paydo bo'ladi. Bizning fikrlarimiz bilan biz dunyoni yaratamiz. - Budda",
                    "Eng qorong'u daqiqalarimizda biz yorug'likni ko'rishga e'tibor qaratishimiz kerak. - Aristotel Onassis",
                    "Sizning hozirgi sharoitingiz qaerga borishingizni aniqlamaydi; ular faqat qaerdan boshlashingizni belgilaydi. - Nido Qubein",
                    "Hamma narsaning go'zalligi bor, lekin uni hamma ham ko'ravermaydi. - Konfutsiy",
                    "Agar rostini aytsangiz, hech narsani eslab qolishingiz shart emas. - Mark Tven",
                    "Qo'lingdan kelmaydigan narsa qila oladigan narsangizga xalaqit berishiga yo'l qo'ymang. - Jon Vuden",
                    "Muvaffaqiyat ishtiyoqni yo'qotmasdan muvaffaqiyatsizlikdan muvaffaqiyatsizlikka o'tishdan iborat. - Uinston Cherchill",
                    "Sizni doimo boshqa narsaga aylantirmoqchi bo'lgan dunyoda o'zingiz bo'lish - bu eng katta yutuq. - Ralf Valdo Emerson",
                    "Shamol yo'nalishini o'zgartira olmaysiz, ammo yelkaningizni har doim manzilingizga etib borish uchun sozlashingiz mumkin. - Jimmi Din",
                    "Agar siz biror narsa uchun turmasangiz, hamma narsaga tushib qolasiz. - Malkolm X",
                    "O'rganilmagan hayot yashashga arzimaydi. - Sokrat",
                    "Muvaffaqiyatsiz bo'lish qiyin, lekin hech qachon muvaffaqiyatga erishmaslik bundan ham yomoni. - Teodor Ruzvelt",
                    "Yashashdagi eng katta shon-shuhrat hech qachon yiqilmasligimizda emas, balki har yiqilganimizda ko'tarilishdadir. - Ralf Valdo Emerson"
                    "Men hayot haqida o'rganganlarimni uchta so'z bilan ifodalashim mumkin: u davom etmoqda. - Robert Frost",
                    "Muvaffaqiyat baxtning kaliti emas. Baxt - muvaffaqiyat kaliti. Agar qilayotgan ishingizni sevsangiz, muvaffaqiyatga erishasiz. - Albert Shvaytser",
                    "Men hayotimda qayta-qayta muvaffaqiyatsizlikka uchraganman va shuning uchun ham muvaffaqiyatga erishdim. - Maykl Jordan",
                    "Biz chekli umidsizlikni qabul qilishimiz kerak, lekin hech qachon cheksiz umidni yo'qotmaslik kerak. - Martin Lyuter King Jr.",
                    "Qaerga borsangiz ham muhabbatni yoying. Hech kim sizning oldingizga baxtliroq kelmasin. - Tereza ona",
                    "O'tmishda o'ylamang, kelajakni orzu qilmang, ongingizni hozirgi daqiqaga qarating. - Budda",
                    "Yuzingizni har doim quyosh nuri tomon yo'naltiring - va sizning orqangizdan soyalar tushadi. - Uolt Uitman",
                    "Siz boshqa maqsadni qo'yish yoki yangi orzuni orzu qilish uchun hech qachon keksa emassiz. - C. S. Lyuis",
                    "Biz nima deb o'ylaymiz, biz bo'lamiz. - Budda",
                    "O'zingizga va bor narsangizga ishoning. Bilingki, ichingizda har qanday to'siqdan ham kattaroq narsa bor. - Kristian D. Larson",
                    "Men sharoitim mahsuli emasman. Men qarorlarim mahsuliman. - Stiven Kovi",
                    "Yagona haqiqiy donolik hech narsa bilmasligingizni bilishdir. - Sokrat"
                    "Vaqtingiz cheklangan, uni boshqa birovning hayotiga sarflamang. - Stiv Jobs",
                    "Hayot bir qator tabiiy va o'z-o'zidan paydo bo'ladigan o'zgarishlardir. Ularga qarshilik qilmang - bu faqat qayg'u keltiradi. Haqiqat haqiqat bo'lsin. Ishlar tabiiy ravishda o'zlari xohlagan tarzda oldinga o'tsin. - Lao Tzu",
                    "Yaxshi fikrga ega bo'lishning yagona yo'li - ko'p g'oyalarga ega bo'lishdir. - Linus Pauling",
                    "Muvaffaqiyatli bo'lishga emas, balki qadrli bo'lishga intiling. - Albert Eynshteyn",
                    "Agar siz orzularingizni ro'yobga chiqarishni istasangiz, birinchi navbatda uyg'onishingiz kerak. - J. M. Pauer",
                    "Har bir kunni yig'ib olgan hosilingiz bilan emas, balki ekkan urug'ingiz bilan baholang. - Robert Lui Stivenson"
                    "Biz ko'p mag'lubiyatlarga duch kelishimiz mumkin, ammo biz mag'lub bo'lmasligimiz kerak. - Maya Anjelu",
                    "Dunyoda ko'rishni xohlagan o'zgarish bo'l. - Mahatma Gandi",
                    "Amal qiladigan ozgina bilim, behuda bilimdan cheksiz qimmatroqdir. - Xalil Gibran",
                    "Ikki narsa cheksizdir: koinot va inson ahmoqligi; va men koinot haqida ishonchim komil emas. - Albert Eynshteyn",
                    "Optimizm - bu muvaffaqiyatga olib keladigan ishonch. Umid va ishonchsiz hech narsa qilib bo'lmaydi. - Helen Keller",
                    "Bizning barcha orzularimiz amalga oshishi mumkin, agar ularga erishish uchun jasoratimiz bo'lsa. - Uolt Disney",
                    "Hayot o'zingni topishdan iborat emas, hayot o'zingni yaratishdan iborat. - Jorj Bernard Shou"
                    "Bu har doim amalga oshmaguncha imkonsiz bo'lib tuyuladi. - Nelson Mandela",
                    "Jasorat har doim ham bo'kmaydi. Ba'zida jasorat kun oxirida ertaga yana urinib ko'raman degan sokin ovozdir. - Meri Enn Radmacher",
                    "Siz va maqsadingiz o'rtasida turgan yagona narsa bu nima uchun bunga erisha olmasligingiz haqida o'zingizga gapiradigan bema'ni hikoyadir. - Jordan Belfort",
                    "Buyuklikdan qo'rqmang. Ba'zilar buyuk bo'lib tug'iladilar, ba'zilari buyuklikka erishadilar, boshqalari esa ulug'vorlikka intilishadi. - Uilyam Shekspir",
                    "Inson faqat o'z fikrlarining mahsuli. U nima o'ylasa, u bo'ladi. - Mahatma Gandi",
                    ]
    return uzbek_quotes